spring.application.name=ms-inventario
server.port=8082

# Configuración de Base de Datos propia para InventarioS
spring.datasource.url=jdbc:h2:mem:inventariodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/